name: risk

services:
  database:
    image: riskpy/risk-database:latest
    build:
      context: .
      dockerfile: ./Dockerfile.database
    pull_policy: build
    ports:
      - 1521:1521
    env_file:
      - ./docker/common.env
      - ./docker/database/.env

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  api:
    image: riskpy/risk-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile.api
    pull_policy: build
    ports:
      - 5000:5000
    env_file:
      - ./docker/common.env
      - ./docker/api/.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: riskpy/risk-frontend:latest
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    pull_policy: build
    ports:
      - 8181:8181
    env_file:
      - ./docker/common.env
      - ./docker/frontend/.env
    depends_on:
      database:
        condition: service_healthy

  mokapi:
    image: mokapi/mokapi:latest
    ports:
      - 8080:8080 # Dashboard
      - 80:80 # HTTP Mock
      - 389:389 # LDAP Mock
      - 25:25 # SMTP Mock
      - 143:143 # IMAP Mock
    volumes:
      - ./docker/mokapi:/mokapi
    environment:
      - MOKAPI_PROVIDERS_FILE_DIRECTORY=/mokapi
